SELECT 
    BOOK.BOOK_ID, 
    BOOK.TITLE, 
    BOOK.ISBN13, 
    BOOK.LANGUAGE_ID,
    BOOK_LANGUAGE.LANGUAGE_CODE, 
    BOOK_LANGUAGE.LANGUAGE_NAME,
    BOOK.PUBLISHER_ID,
    PUBLISHER.PUBLISHER_NAME
FROM BOOK
INNER JOIN BOOK_LANGUAGE 
    ON BOOK.LANGUAGE_ID = BOOK_LANGUAGE.LANGUAGE_ID
INNER JOIN PUBLISHER
    ON BOOK.PUBLISHER_ID = PUBLISHER.PUBLISHER_ID;


SELECT * FROM AUTHOR;

SELECT 
    BOOK.BOOK_ID, 
    BOOK.TITLE, 
    BOOK.ISBN13, 
    BOOK.LANGUAGE_ID,
    BOOK_LANGUAGE.LANGUAGE_CODE, 
    BOOK_LANGUAGE.LANGUAGE_NAME,
    BOOK.PUBLISHER_ID,
    PUBLISHER.PUBLISHER_NAME
    FROM BOOK
    INNER JOIN BOOK_LANGUAGE 
        ON BOOK.LANGUAGE_ID = BOOK_LANGUAGE.LANGUAGE_ID
    INNER JOIN PUBLISHER
        ON BOOK.PUBLISHER_ID = PUBLISHER.PUBLISHER_ID;

SELECT 
    CUSTOMER.CUSTOMER_ID,
    CUSTOMER.FIRST_NAME,
    CUSTOMER.LAST_NAME,
    CUSTOMER.EMAIL
FROM CUSTOMER;

SELECT 
    CUSTOMER_ADDRESS.ADDRESS_ID,
    ADDRESS_STATUS.ADDRESS_STATUS,
    CUSTOMER_ADDRESS.STATUS_ID,
    ADDRESS.STREET_NUMBER,
    ADDRESS.STREET_NAME,
    ADDRESS.CITY,
    ADDRESS.COUNTRY_ID,
    COUNTRY.COUNTRY_NAME
FROM CUSTOMER_ADDRESS
    INNER JOIN ADDRESS_STATUS
        ON CUSTOMER_ADDRESS.STATUS_ID = ADDRESS_STATUS.STATUS_ID
    INNER JOIN ADDRESS
        ON CUSTOMER_ADDRESS.ADDRESS_ID = ADDRESS.ADDRESS_ID
    INNER JOIN COUNTRY
        ON ADDRESS.COUNTRY_ID = COUNTRY.COUNTRY_ID
    WHERE CUSTOMER_ADDRESS.CUSTOMER_ID = 1;

SELECT
    CUST_ORDER.ORDER_ID
FROM CUST_ORDER
    WHERE CUST_ORDER.CUSTOMER_ID = 1;

SELECT 
    CUST_ORDER.ORDER_ID,
    CUST_ORDER.ORDER_DATE,
    SHIPPING_METHOD.METHOD_ID,
    SHIPPING_METHOD.METHOD_NAME,
    SHIPPING_METHOD.COST
FROM CUST_ORDER
    INNER JOIN SHIPPING_METHOD
        ON CUST_ORDER.SHIPPING_METHOD_ID = SHIPPING_METHOD.METHOD_ID;


SELECT
    ORDER_HISTORY.HISTORY_ID,
    ORDER_HISTORY.ORDER_ID,
    ORDER_HISTORY.STATUS_ID,
    ORDER_HISTORY.STATUS_DATE,
    ORDER_STATUS.STATUS_ID,
    ORDER_STATUS.STATUS_VALUE
FROM ORDER_HISTORY 
    INNER JOIN ORDER_STATUS
        ON ORDER_HISTORY.STATUS_ID = ORDER_STATUS.STATUS_ID
    WHERE ORDER_HISTORY.ORDER_ID = 1;


SELECT
    ORDER_LINE.LINE_ID,
    ORDER_LINE.BOOK_ID,
    ORDER_LINE.PRICE
FROM ORDER_LINE
    WHERE ORDER_LINE.ORDER_ID = 1;



    SELECT
        ORDER_STATUS.STATUS_ID,
        ORDER_STATUS.STATUS_VALUE
    FROM ORDER_STATUS ;

SELECT * FROM ADDRESS INNER JOIN COUNTRY ON ADDRESS.COUNTRY_ID = COUNTRY.COUNTRY_ID ;

    SELECT BOOK_AUTHOR.BOOK_ID,
        BOOK_AUTHOR.AUTHOR_ID
    FROM BOOK_AUTHOR;


    SELECT * FROM CUSTOMER_ADDRESS
    INNER JOIN ADDRESS_STATUS ON CUSTOMER_ADDRESS.STATUS_ID = ADDRESS_STATUS.STATUS_ID;



SELECT * FROM ORDER_LINE;
SELECT * FROM ORDER_HISTORY;
SELECT * FROM CUST_ORDER;

    SELECT * FROM CUSTOMER_ADDRESS
    INNER JOIN ADDRESS_STATUS ON CUSTOMER_ADDRESS.STATUS_ID = ADDRESS_STATUS.STATUS_ID;